# Basic Metadata configuration
baseURL = 'https://spshreyas.in'
languageCode = 'en-us'
title = 'Shreyas S P'
theme = 'hugobear'
author = 'Shreyas S P'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/blog/:slug/"
  tags = "/tags/:slug"

[params.social]
  linkedin = "https://www.linkedin.com/in/shreyasparamesh/"
  twitter = "https://x.com/sp_shreyas_"
  facebook = "https://www.facebook.com/shreyas.sp.gowda"
  instagram = "https://www.instagram.com/sp.shreyas"

[markup.goldmark.renderer]
unsafe= true